In [1]:
pip install pandas numpy

Requirement already satisfied: pandas in c:\users\elcot\desktop\sasirekha-g40 aiml 7\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\elcot\desktop\sasirekha-g40 aiml 7\.venv\lib\site-packages (2.2.6)
Requirement already satisfied: tzdata>=2022.7 in c:\users\elcot\desktop\sasirekha-g40 aiml 7\.venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\elcot\desktop\sasirekha-g40 aiml 7\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\elcot\desktop\sasirekha-g40 aiml 7\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\elcot\desktop\sasirekha-g40 aiml 7\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [ ]:
# Read the dataset using relative directory traversal paths
df = pd.read_csv(r"C:\Users\ELCOT\Desktop\Sasirekha-G40 AIML 7\data\SmartShop_Portfolio_Dataset.csv")

In [4]:
df.head()

,Interaction_ID,Customer_ID,Product_ID,Category,Brand,Age,Gender,Region,Membership,Season,Holiday,Price,Discount,Views,Time_On_Page,Wishlist,Added_To_Cart,Previous_Purchases,Average_Order_Value,Days_Since_Last_Purchase,Recommendation_Score,Purchase_Status,Product_Rating,Customer_Lifetime_Value,Churn_Risk,Campaign_Response,Device,Payment_Method,Stock_Level,Delivery_Days
0,1,100001,4582,Books,PrimeGear,56,Male,South,Silver,Winter,0,47.27,10,16,479,0,1,3,42.54,302,54,0,3.7,138.29,42,1,Mobile,Card,357,7
1,2,100002,8527,Fashion,FreshMart,23,Female,East,Bronze,Summer,0,241.66,30,22,66,1,1,0,169.16,339,53,0,4.0,176.18,42,0,Desktop,UPI,437,4
2,3,100003,3677,Toys,FreshMart,35,Male,East,Gold,Spring,0,576.39,15,24,52,1,1,9,489.93,162,91,1,4.7,4254.82,7,1,Desktop,UPI,108,10
3,4,100004,5304,Grocery,EcoLife,43,Female,South,Gold,Summer,1,478.87,25,32,113,0,1,7,359.15,25,83,1,3.9,3154.76,20,0,Mobile,Card,405,7
4,5,100005,6573,Fashion,BookNest,45,Male,West,Silver,Spring,1,583.30,20,30,532,0,1,6,466.64,92,90,1,5.0,3594.27,15,0,Tablet,Wallet,430,9

In [5]:
# Display structural rows from the trailing end of the frame
df.tail()

,Interaction_ID,Customer_ID,Product_ID,Category,Brand,Age,Gender,Region,Membership,Season,Holiday,Price,Discount,Views,Time_On_Page,Wishlist,Added_To_Cart,Previous_Purchases,Average_Order_Value,Days_Since_Last_Purchase,Recommendation_Score,Purchase_Status,Product_Rating,Customer_Lifetime_Value,Churn_Risk,Campaign_Response,Device,Payment_Method,Stock_Level,Delivery_Days
14995,14996,114996,4424,Sports,FreshMart,61,Male,East,Bronze,Spring,0,1049.05,0,5,375,0,0,0,1049.05,301,65,0,3.7,984.76,32,1,Mobile,Wallet,84,3
14996,14997,114997,3925,Grocery,UrbanWear,53,Male,North,Silver,Autumn,0,542.43,20,34,44,1,1,7,433.94,345,75,1,3.9,3712.41,28,1,Tablet,Wallet,478,4
14997,14998,114998,6884,Books,EcoLife,21,Male,East,Bronze,Winter,0,692.52,5,10,589,1,0,0,657.89,133,47,0,3.3,697.48,49,0,Tablet,Card,200,9
14998,14999,114999,8810,Toys,NovaTech,50,Female,East,Silver,Spring,1,33.36,25,3,159,1,0,7,25.02,14,69,0,4.0,217.37,31,0,Mobile,COD,341,4
14999,15000,115000,4764,Toys,BookNest,31,Male,West,Bronze,Winter,0,498.67,10,23,213,1,0,3,448.80,138,62,0,3.9,1829.32,43,1,Tablet,COD,318,3

In [6]:
print("Rows    :", df.shape[0])
print("Columns :", df.shape[1])

Rows    : 15000
Columns : 30

In [7]:
# List complete set of available schema headers
df.columns

Index(['Interaction_ID', 'Customer_ID', 'Product_ID', 'Category', 'Brand',
       'Age', 'Gender', 'Region', 'Membership', 'Season', 'Holiday', 'Price',
       'Discount', 'Views', 'Time_On_Page', 'Wishlist', 'Added_To_Cart',
       'Previous_Purchases', 'Average_Order_Value', 'Days_Since_Last_Purchase',
       'Recommendation_Score', 'Purchase_Status', 'Product_Rating',
       'Customer_Lifetime_Value', 'Churn_Risk', 'Campaign_Response', 'Device',
       'Payment_Method', 'Stock_Level', 'Delivery_Days'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Interaction_ID            15000 non-null  int64
 1   Customer_ID               15000 non-null  int64
 2   Product_ID                15000 non-null  int64
 3   Category                  15000 non-null  object
 4   Brand                     15000 non-null  object
 5   Age                       15000 non-null  int64
 6   Gender                    15000 non-null  object
 7   Region                    15000 non-null  object
 8   Membership                15000 non-null  object
 9   Season                    15000 non-null  object
 10  Holiday                   15000 non-null  int64
 11  Price                     15000 non-null  float64
 12  Discount                  15000 non-null  int64
 13  Views                     15000 non-null  int64
 14  Time_On_Page              15000 non-null  int64
 15  Wishlist                  15000 non-null  int64
 16  Added_To_Cart             15000 non-null  int64
 17  Previous_Purchases        15000 non-null  int64
 18  Average_Order_Value       15000 non-null  float64
 19  Days_Since_Last_Purchase  15000 non-null  int64
 20  Recommendation_Score      15000 non-null  int64
 21  Purchase_Status           15000 non-null  int64
 22  Product_Rating            15000 non-null  float64
 23  Customer_Lifetime_Value   15000 non-null  float64
 24  Churn_Risk                15000 non-null  int64
 25  Campaign_Response         15000 non-null  int64
 26  Device                    15000 non-null  object
 27  Payment_Method            15000 non-null  object
 28  Stock_Level               15000 non-null  int64
 29  Delivery_Days             15000 non-null  int64
dtypes: float64(4), int64(18), object(8)
memory usage: 3.4+ MB

In [10]:
missing = df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [11]:
missing_percent = (df.isnull().sum()/len(df))*100

missing_percent.sort_values(ascending=False)

Interaction_ID              0.0
Customer_ID                 0.0
Product_ID                  0.0
Category                    0.0
Brand                       0.0
Age                         0.0
Gender                      0.0
Region                      0.0
Membership                  0.0
Season                      0.0
Holiday                     0.0
Price                       0.0
Discount                    0.0
Views                       0.0
Time_On_Page                0.0
Wishlist                    0.0
Added_To_Cart               0.0
Previous_Purchases          0.0
Average_Order_Value         0.0
Days_Since_Last_Purchase    0.0
Recommendation_Score        0.0
Purchase_Status             0.0
Product_Rating              0.0
Customer_Lifetime_Value     0.0
Churn_Risk                  0.0
Campaign_Response           0.0
Device                      0.0
Payment_Method              0.0
Stock_Level                 0.0
Delivery_Days               0.0
dtype: float64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe()

,Interaction_ID,Customer_ID,Product_ID,Age,Holiday,Price,Discount,Views,Time_On_Page,Wishlist,Added_To_Cart,Previous_Purchases,Average_Order_Value,Days_Since_Last_Purchase,Recommendation_Score,Purchase_Status,Product_Rating,Customer_Lifetime_Value,Churn_Risk,Campaign_Response,Stock_Level,Delivery_Days
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,7500.500000,107500.500000,5530.472067,41.435400,0.499000,755.776302,14.895667,20.611200,308.111067,0.393200,0.559733,6.774267,642.952448,183.998467,75.590333,0.576133,4.122333,5003.568339,24.705000,0.502200,248.038733,5.500600
std,4330.271354,4330.271354,2599.804116,13.887573,0.500016,427.023258,10.029996,11.501475,167.260042,0.488477,0.496436,6.130901,373.466646,105.221575,17.251155,0.494186,0.526547,5492.724954,17.146964,0.500012,143.447665,2.873236
min,1.000000,100001.000000,1000.000000,18.000000,0.000000,10.180000,0.000000,1.000000,20.000000,0.000000,0.000000,0.000000,7.630000,1.000000,23.000000,0.000000,2.500000,8.770000,1.000000,0.000000,0.000000,1.000000
25%,3750.750000,103750.750000,3295.750000,29.000000,0.000000,387.167500,5.000000,11.000000,163.000000,0.000000,0.000000,2.000000,323.777500,93.000000,63.000000,0.000000,3.800000,1052.355000,10.000000,0.000000,125.000000,3.000000
50%,7500.500000,107500.500000,5573.000000,41.000000,0.000000,757.235000,15.000000,21.000000,308.000000,0.000000,1.000000,5.000000,636.000000,184.000000,76.000000,1.000000,4.100000,3034.980000,24.000000,1.000000,248.000000,6.000000
75%,11250.250000,111250.250000,7783.000000,53.000000,1.000000,1124.062500,25.000000,30.000000,452.000000,1.000000,1.000000,10.000000,940.372500,275.000000,90.000000,1.000000,4.500000,6990.035000,37.000000,1.000000,370.000000,8.000000
max,15000.000000,115000.000000,9998.000000,65.000000,1.000000,1499.990000,30.000000,40.000000,600.000000,1.000000,1.000000,29.000000,1499.990000,365.000000,100.000000,1.000000,5.000000,39775.580000,80.000000,1.000000,500.000000,10.000000

In [14]:
df.describe(include="all")

,Interaction_ID,Customer_ID,Product_ID,Category,Brand,Age,Gender,Region,Membership,Season,Holiday,Price,Discount,Views,Time_On_Page,Wishlist,Added_To_Cart,Previous_Purchases,Average_Order_Value,Days_Since_Last_Purchase,Recommendation_Score,Purchase_Status,Product_Rating,Customer_Lifetime_Value,Churn_Risk,Campaign_Response,Device,Payment_Method,Stock_Level,Delivery_Days
count,15000.000000,15000.000000,15000.000000,15000,15000,15000.000000,15000,15000,15000,15000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000,15000,15000.000000,15000.000000
unique,NaN,NaN,NaN,8,10,NaN,2,4,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,4,NaN,NaN
top,NaN,NaN,NaN,Toys,KitchenPro,NaN,Female,South,Bronze,Spring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mobile,Wallet,NaN,NaN
freq,NaN,NaN,NaN,1918,1576,NaN,7506,3837,5993,3824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5106,3846,NaN,NaN
mean,7500.500000,107500.500000,5530.472067,NaN,NaN,41.435400,NaN,NaN,NaN,NaN,0.499000,755.776302,14.895667,20.611200,308.111067,0.393200,0.559733,6.774267,642.952448,183.998467,75.590333,0.576133,4.122333,5003.568339,24.705000,0.502200,NaN,NaN,248.038733,5.500600
std,4330.271354,4330.271354,2599.804116,NaN,NaN,13.887573,NaN,NaN,NaN,NaN,0.500016,427.023258,10.029996,11.501475,167.260042,0.488477,0.496436,6.130901,373.466646,105.221575,17.251155,0.494186,0.526547,5492.724954,17.146964,0.500012,NaN,NaN,143.447665,2.873236
min,1.000000,100001.000000,1000.000000,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,0.000000,10.180000,0.000000,1.000000,20.000000,0.000000,0.000000,0.000000,7.630000,1.000000,23.000000,0.000000,2.500000,8.770000,1.000000,0.000000,NaN,NaN,0.000000,1.000000
25%,3750.750000,103750.750000,3295.750000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,0.000000,387.167500,5.000000,11.000000,163.000000,0.000000,0.000000,2.000000,323.777500,93.000000,63.000000,0.000000,3.800000,1052.355000,10.000000,0.000000,NaN,NaN,125.000000,3.000000
50%,7500.500000,107500.500000,5573.000000,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,0.000000,757.235000,15.000000,21.000000,308.000000,0.000000,1.000000,5.000000,636.000000,184.000000,76.000000,1.000000,4.100000,3034.980000,24.000000,1.000000,NaN,NaN,248.000000,6.000000
75%,11250.250000,111250.250000,7783.000000,NaN,NaN,53.000000,NaN,NaN,NaN,NaN,1.000000,1124.062500,25.000000,30.000000,452.000000,1.000000,1.000000,10.000000,940.372500,275.000000,90.000000,1.000000,4.500000,6990.035000,37.000000,1.000000,NaN,NaN,370.000000,8.000000
max,15000.000000,115000.000000,9998.000000,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,1.000000,1499.990000,30.000000,40.000000,600.000000,1.000000,1.000000,29.000000,1499.990000,365.000000,100.000000,1.000000,5.000000,39775.580000,80.000000,1.000000,NaN,NaN,500.000000,10.000000

In [15]:
df.nunique()

Interaction_ID              15000
Customer_ID                 15000
Product_ID                   7274
Category                        8
Brand                          10
Age                            48
Gender                          2
Region                          4
Membership                      4
Season                          4
Holiday                         2
Price                       14258
Discount                        7
Views                          40
Time_On_Page                  581
Wishlist                        2
Added_To_Cart                   2
Previous_Purchases             30
Average_Order_Value         14179
Days_Since_Last_Purchase      365
Recommendation_Score           78
Purchase_Status                 2
Product_Rating                 26
Customer_Lifetime_Value     14875
Churn_Risk                     79
Campaign_Response               2
Device                          3
Payment_Method                  4
Stock_Level                   501
Delivery_Days                  10
dtype: int64

In [16]:
df["Category"].value_counts()

Category
Toys           1918
Sports         1897
Beauty         1890
Home           1888
Grocery        1878
Electronics    1859
Books          1846
Fashion        1824
Name: count, dtype: int64

In [17]:
df["Brand"].value_counts()

df["Membership"].value_counts()

df["Device"].value_counts()

df["Payment_Method"].value_counts()

Payment_Method
Wallet    3846
COD       3747
UPI       3722
Card      3685
Name: count, dtype: int64

In [18]:
report = pd.DataFrame({
    "Data Type": df.dtypes,
    "Missing Values": df.isnull().sum(),
    "Unique Values": df.nunique()
})

In [19]:
report

                         Data Type  Missing Values  Unique Values
Interaction_ID               int64               0          15000
Customer_ID                  int64               0          15000
Product_ID                   int64               0           7274
Category                    object               0              8
Brand                       object               0             10
Age                          int64               0             48
Gender                      object               0              2
Region                      object               0              4
Membership                  object               0              4
Season                      object               0              4
Holiday                      int64               0              2
Price                      float64               0          14258
Discount                     int64               0              7
Views                        int64               0             40
Time_On_Page                 int64               0            581
Wishlist                     int64               0              2
Added_To_Cart                int64               0              2
Previous_Purchases           int64               0             30
Average_Order_Value        float64               0          14179
Days_Since_Last_Purchase     int64               0            365
Recommendation_Score         int64               0             78
Purchase_Status              int64               0              2
Product_Rating             float64               0             26
Customer_Lifetime_Value    float64               0          14875
Churn_Risk                   int64               0             79
Campaign_Response            int64               0              2
Device                      object               0              3
Payment_Method              object               0              4
Stock_Level                  int64               0            501
Delivery_Days                int64               0             10

In [25]:
report.to_csv(r"C:\Users\ELCOT\Desktop\Sasirekha-G40 AIML 7\outputs\figures\reports\Data_Quality_Report.csv", index=False)

The dataset contains customer interaction records from an e-commerce platform.
Both numerical and categorical variables are present.
Product_Rating is the target for regression.
Purchase_Status is the target for classification.
Customer behavior features can be used for K-Means clustering.
Data quality has been assessed by checking missing values, duplicates, and data types.